### ISSUE TITLE
Single-line values with links don't come through properly

### ISSUE THREAD

**Issue by kevinschaul** [WPMedia/driveshaft#2]
Seems to be an issue with the html link -> text conversion, not necessarily the text -> archieml conversion.

Doesn't work:

authors: [Amber Phillips](http://www.washingtonpost.com/people/amber-phillips)

Works:

authors: [Amber Phillips](http://www.washingtonpost.com/people/amber-phillips)
:end

**Comment by kevinschaul** [comment]
https://github.com/newsdev/driveshaft/pull/29

**Comment by jmuyskens** [comment]
https://github.com/WPMedia/driveshaft/commit/b0fa18964f12d44c9dd5a9c56e5f97324c968c53
